name: Write CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: git clone --recurse-submodules https://github.com/styluslabs/Write
    #- uses: actions/checkout@v4
    #  with:
    #    submodules: recursive
    - run: git switch write-linux
      working-directory: Write/SDL
    - run: make DEBUG=1
      working-directory: Write/syncscribble
    - run: ./Debug/Write --test
      working-directory: Write/syncscribble
