name: Write CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: git switch write-linux
      working-directory: SDL
    - run: make DEBUG=1
      working-directory: syncscribble
    - run: ./Debug/Write --test
      working-directory: syncscribble
